analytics: {}
color:
  brandColors:
    - '#D0C8A8'
    - '#601010'
    - '#909850'
    - '#F85020'
    - '#F08848'
  brandStrength: 0.33277
  lightness: 0.625
  rhythmicContrast: 0.221284
  saturation: 0.347128
cta: {}
layout_spectrum: 0.767736
name: ideas2earth.com
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.704392
