analytics: {}
color:
  brandColors:
    - '#D0C8A8'
    - '#601010'
    - '#909850'
    - '#F85020'
    - '#F08848'
  brandStrength: 0.6875
  lightness: 0.625
  rhythmicContrast: 0.5
  saturation: 0.75
cta: {}
layout_spectrum: 0.37318
name: ideas2earth.com
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.60603
