name: ideas2earth
favicon: null
layout_spectrum: 0.37318
typography_spectrum: 0.60603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1009'
    - '#ffffff'
    - '#9e836f'
    - '#ccab92'
    - '#fc835f'
  brandStrength: 0.5625
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
