name: ideas2earth
favicon: null
layout_spectrum: 0.37318
typography_spectrum: 0.60603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9e4ce'
    - '#060845'
    - '#176a61'
    - '#dd9b8a'
    - '#88254a'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
