analytics: {}
color:
  brandColors:
    - '#C0B8B8'
    - '#803030'
    - '#A86070'
    - '#A83840'
    - '#C87870'
  brandStrength: 0.890726
  lightness: 0.831106
  rhythmicContrast: 0.038592
  saturation: 0.541108
cta: {}
layout_spectrum: 0.615709
name: ideas2earth
opengraph: {}
purpose: {}
typography_spectrum: 0.980574
